### ISSUE TITLE
Initial Repository and File Structure Set Up

### ISSUE THREAD

**Issue by natakkuma** [ngranzow/gas-guzzlers#1]
Create Team Repository.
Invite Team Members.
Create Initial File Structure & Folders: model. config, controllers, public, utils, views, package.json, sever.js

**Comment by christine-zhe** [comment]
Application has a folder structure that meets the MVC paradigm and uses Handlebars.js as the template engine.

**Comment by natakkuma** [comment]
Nate completed.
